### Imports

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### Code pour générer des fausses données

In [5]:
def fake_matrix(nb_products = 6,
                nb_cust = 5,
                share_empty = 0.7):

    name_products = ["P"+str(x+1) for x in range(nb_products)]
    name_cust = ["cust_"+str(x+1) for x in range(nb_cust)]

    rand = np.random.rand(nb_cust,nb_products)
    empty = np.random.rand(nb_cust,nb_products)>share_empty

    fake_matrix = pd.DataFrame(rand*empty,
                               index=name_cust,
                               columns=name_products
                              )


    return fake_matrix

In [6]:
fake_data = fake_matrix(100, 100, 0.7)
display(fake_data)

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P91,P92,P93,P94,P95,P96,P97,P98,P99,P100
cust_1,0.000000,0.000000,0.000000,0.000000,0.068043,0.365644,0.000000,0.000000,0.080876,0.000000,...,0.000000,0.664038,0.300865,0.148108,0.909276,0.300351,0.000000,0.000000,0.000000,0.0
cust_2,0.337949,0.000000,0.000000,0.389758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.142672,0.000000,0.144262,0.000000,0.0
cust_3,0.000000,0.218191,0.000000,0.502589,0.000000,0.849044,0.000000,0.131197,0.000000,0.446769,...,0.000000,0.000000,0.293301,0.000000,0.904695,0.000000,0.000000,0.000000,0.000000,0.0
cust_4,0.000000,0.351922,0.000000,0.000000,0.456996,0.000000,0.999998,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.347086,0.000000,0.000000,0.000000,0.322332,0.000000,0.754229,0.0
cust_5,0.900272,0.000000,0.000000,0.080377,0.085035,0.000000,0.000000,0.000000,0.000000,0.040043,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.314394,0.260991,0.604536,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cust_96,0.000000,0.000000,0.552662,0.000000,0.000000,0.819958,0.245023,0.513401,0.710463,0.000000,...,0.571222,0.000000,0.741563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
cust_97,0.000000,0.911027,0.570600,0.579970,0.198603,0.508049,0.000000,0.000000,0.000000,0.206778,...,0.440015,0.000000,0.000000,0.000000,0.984769,0.000000,0.000000,0.000000,0.000000,0.0
cust_98,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.519662,...,0.000000,0.000000,0.524624,0.352743,0.878146,0.391334,0.464863,0.385167,0.000000,0.0
cust_99,0.736507,0.000000,0.718666,0.000000,0.704775,0.000000,0.000000,0.242214,0.000000,0.000000,...,0.000000,0.274493,0.000000,0.763998,0.128535,0.000000,0.699779,0.000000,0.000000,0.0
cust_100,0.000000,0.854437,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.772958,...,0.000000,0.000000,0.000000,0.822944,0.781850,0.000000,0.411945,0.000000,0.063611,0.0

### Méthode corrélation de Pearson

In [7]:
from sklearn.feature_selection import r_regression as pearson_correlation

In [75]:
data = fake_data.copy()

In [76]:
# On transpose la matrice, parceque la fonction pearson fait une correlation entre les colonnes
data_transposed = data.transpose()

# L'utilisateur à qui on va faire des recommandations
utilisateur = 'cust_5'

# On fait la corrélation de cust_5 avec toutes les autres colonnes
correlations = pearson_correlation(data_transposed, data_transposed[utilisateur])

# On reformate pour avoir les données dans un dataframe propre
correlations_col = pd.DataFrame(index=data.index)
correlations_col['correlations'] = correlations
correlations_col

          correlations
cust_1       -0.039389
cust_2       -0.005168
cust_3       -0.032590
cust_4       -0.040572
cust_5        1.000000
...                ...
cust_96       0.018606
cust_97       0.031028
cust_98      -0.098136
cust_99       0.043532
cust_100     -0.172716

[100 rows x 1 columns]

In [77]:
# On trie par ordre décroissant
sorted_correlations = correlations_col.sort_values('correlations', ascending=False)
sorted_correlations

          correlations
cust_5        1.000000
cust_66       0.216714
cust_51       0.201796
cust_46       0.190862
cust_23       0.178074
...                ...
cust_8       -0.167448
cust_95      -0.168490
cust_25      -0.169417
cust_100     -0.172716
cust_40      -0.223542

[100 rows x 1 columns]

In [41]:
# Là, on a cust_5 en premier (qu'on peut ignorer), et ensuite les utilisateurs les plus proches
# Du coup, on prend ceux là, et on veut les scores qu'ils donnent à des objets

In [78]:
# On prend les 5 utilisateurs les plus proches
n_utilisateurs_proches = 5

utilisateurs_proches = sorted_correlations[1:n_utilisateurs_proches+1].index

In [80]:
utilisateurs_proches

Index(['cust_66', 'cust_51', 'cust_46', 'cust_23', 'cust_38'], dtype='object')

In [81]:
# On ne garde que les ratings de ces utilisateurs
data_utilisateurs_proches = data.filter(items=utilisateurs_proches, axis=0).transpose()
data_utilisateurs_proches

       cust_66   cust_51   cust_46   cust_23   cust_38
P1    0.000000  0.631290  0.000000  0.816183  0.905864
P2    0.000000  0.962201  0.248356  0.000000  0.492809
P3    0.000000  0.000000  0.000000  0.000000  0.534131
P4    0.412582  0.000000  0.652851  0.000000  0.000000
P5    0.242166  0.000000  0.000000  0.000000  0.000000
...        ...       ...       ...       ...       ...
P96   0.000000  0.000000  0.000000  0.012577  0.426437
P97   0.000000  0.000000  0.000000  0.000000  0.000000
P98   0.000000  0.476468  0.000000  0.000000  0.000000
P99   0.000000  0.000000  0.900794  0.000000  0.000000
P100  0.000000  0.000000  0.814439  0.000000  0.000000

[100 rows x 5 columns]

In [82]:
# Les ratings de notre utilisateur
data_utilisateur = data.filter(items=[utilisateur], axis=0).transpose()
data_utilisateur

        cust_5
P1    0.900272
P2    0.000000
P3    0.000000
P4    0.080377
P5    0.085035
...        ...
P96   0.314394
P97   0.260991
P98   0.604536
P99   0.000000
P100  0.000000

[100 rows x 1 columns]

In [75]:
# Au final, on va recommander:
# Les items que les utilisateurs proches ont notés
# Que l'utilisateur lui-même n'a pas déjà noté
# Triés par note décroissante ? Par nombre d'utilisateurs qui recommandent ?

In [90]:
# Nombre d'utilisateurs proches qui ont noté
n_ratings = (data_utilisateurs_proches != 0).sum(axis=1)

# Note moyenne
mean_ratings = (data_utilisateurs_proches[data_utilisateurs_proches != 0]).mean(axis=1)

utilisateur_has_rated = (data_utilisateur[utilisateur] != 0)

data_utilisateur['n_ratings'] = n_ratings
data_utilisateur['mean_ratings'] = mean_ratings
data_utilisateur['has_rated'] = utilisateur_has_rated

In [91]:
items_sorted = data_utilisateur[data_utilisateur['has_rated'] == False].sort_values(['mean_ratings'], ascending=False)
items_sorted

     cust_5  n_ratings  mean_ratings  has_rated
P75     0.0          1      0.995797      False
P34     0.0          1      0.933413      False
P99     0.0          1      0.900794      False
P92     0.0          1      0.838894      False
P94     0.0          1      0.829852      False
..      ...        ...           ...        ...
P81     0.0          0           NaN      False
P82     0.0          0           NaN      False
P86     0.0          0           NaN      False
P91     0.0          0           NaN      False
P95     0.0          0           NaN      False

[65 rows x 4 columns]

In [92]:
# Les items à recommander sont les premiers items de la liste
items_sorted[:5].index

Index(['P75', 'P34', 'P99', 'P92', 'P94'], dtype='object')

In [95]:
# On mets le tout dans une fonction
def person_based_recommandation(data, utilisateur, n_proches=5, n_recommandations=5):
    # On transpose la matrice, parceque la fonction pearson fait une correlation entre les colonnes
    data_transposed = data.transpose()

    # On fait la corrélation de cust_5 avec toutes les autres colonnes
    correlations = pearson_correlation(data_transposed, data_transposed[utilisateur])

    # On reformate pour avoir les données dans un dataframe propre
    correlations_col = pd.DataFrame(index=data.index)
    correlations_col['correlations'] = correlations

    # On trie par ordre décroissant
    sorted_correlations = correlations_col.sort_values('correlations', ascending=False)
    
    utilisateurs_proches = sorted_correlations[1:n_proches+1].index
    
    # On ne garde que les ratings de ces utilisateurs
    data_utilisateurs_proches = data.filter(items=utilisateurs_proches, axis=0).transpose()
    
    # Les ratings de notre utilisateur
    data_utilisateur = data.filter(items=[utilisateur], axis=0).transpose()

    # Nombre d'utilisateurs proches qui ont noté
    n_ratings = (data_utilisateurs_proches != 0).sum(axis=1)

    # Note moyenne
    mean_ratings = (data_utilisateurs_proches[data_utilisateurs_proches != 0]).mean(axis=1)

    utilisateur_has_rated = (data_utilisateur[utilisateur] != 0)

    data_utilisateur['n_ratings'] = n_ratings
    data_utilisateur['mean_ratings'] = mean_ratings
    data_utilisateur['has_rated'] = utilisateur_has_rated
    
    items_sorted = data_utilisateur[data_utilisateur['has_rated'] == False].sort_values(['mean_ratings'], ascending=False)

    return items_sorted[:n_recommandations].index

In [96]:
# Exemples
person_based_recommandation(fake_data, 'cust_5')

Index(['P75', 'P34', 'P99', 'P92', 'P94'], dtype='object')

In [70]:
person_based_recommandation(fake_data, 'cust_75', n_proches=15, n_recommandations=8)

Index(['P53', 'P74', 'P32', 'P35', 'P97', 'P25', 'P8', 'P31'], dtype='object')

### Non Negative Factorization

In [20]:
from sklearn.decomposition import NMF

In [21]:
data = fake_data.copy()

In [22]:
data

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P91,P92,P93,P94,P95,P96,P97,P98,P99,P100
cust_1,0.000000,0.000000,0.000000,0.000000,0.068043,0.365644,0.000000,0.000000,0.080876,0.000000,...,0.000000,0.664038,0.300865,0.148108,0.909276,0.300351,0.000000,0.000000,0.000000,0.0
cust_2,0.337949,0.000000,0.000000,0.389758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.142672,0.000000,0.144262,0.000000,0.0
cust_3,0.000000,0.218191,0.000000,0.502589,0.000000,0.849044,0.000000,0.131197,0.000000,0.446769,...,0.000000,0.000000,0.293301,0.000000,0.904695,0.000000,0.000000,0.000000,0.000000,0.0
cust_4,0.000000,0.351922,0.000000,0.000000,0.456996,0.000000,0.999998,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.347086,0.000000,0.000000,0.000000,0.322332,0.000000,0.754229,0.0
cust_5,0.900272,0.000000,0.000000,0.080377,0.085035,0.000000,0.000000,0.000000,0.000000,0.040043,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.314394,0.260991,0.604536,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cust_96,0.000000,0.000000,0.552662,0.000000,0.000000,0.819958,0.245023,0.513401,0.710463,0.000000,...,0.571222,0.000000,0.741563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
cust_97,0.000000,0.911027,0.570600,0.579970,0.198603,0.508049,0.000000,0.000000,0.000000,0.206778,...,0.440015,0.000000,0.000000,0.000000,0.984769,0.000000,0.000000,0.000000,0.000000,0.0
cust_98,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.519662,...,0.000000,0.000000,0.524624,0.352743,0.878146,0.391334,0.464863,0.385167,0.000000,0.0
cust_99,0.736507,0.000000,0.718666,0.000000,0.704775,0.000000,0.000000,0.242214,0.000000,0.000000,...,0.000000,0.274493,0.000000,0.763998,0.128535,0.000000,0.699779,0.000000,0.000000,0.0
cust_100,0.000000,0.854437,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.772958,...,0.000000,0.000000,0.000000,0.822944,0.781850,0.000000,0.411945,0.000000,0.063611,0.0

In [43]:
# On va factoriser la matrice des poids en deux matrices W et H, de plus petite taille
# La taille intermédiaire correspond à des "catégories" (d'utilisateurs et d'items)
n_categories = 5
model = NMF(n_components=n_categories, init='random', random_state=0)
W = model.fit_transform(data)
H = model.components_

In [44]:
# On refait des DataFrames avec les noms de lignes/colonnes initiaux
W_df = pd.DataFrame(W, index=data.index)
W_df

                 0         1         2         3         4
cust_1    0.146988  0.172422  0.176579  0.345724  0.095254
cust_2    0.000000  0.000000  0.650588  0.173861  0.216470
cust_3    0.080214  0.251487  0.000000  0.437603  0.019148
cust_4    0.003079  0.558261  0.134800  0.003410  0.538411
cust_5    0.735472  0.342786  0.226731  0.016360  0.006197
...            ...       ...       ...       ...       ...
cust_96   0.420610  0.039296  0.190951  0.000000  0.332167
cust_97   0.739960  0.000000  0.000000  0.546598  0.000000
cust_98   0.128159  0.248673  0.000000  0.539426  0.000000
cust_99   0.195933  0.459099  0.000000  0.022002  0.439858
cust_100  0.000000  0.396043  0.000000  0.474557  0.060985

[100 rows x 5 columns]

In [45]:
H_df = pd.DataFrame(H, columns=data.columns)
H_df

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P91,P92,P93,P94,P95,P96,P97,P98,P99,P100
0,0.143253,0.040559,0.167968,0.227983,0.265636,0.192041,0.081427,0.160180,0.208052,0.000000,...,0.000000,0.006988,0.149944,0.018156,0.000000,0.456723,0.021372,0.122529,0.000000,0.046971
1,0.132906,0.060577,0.153259,0.000000,0.140401,0.216326,0.324246,0.090825,0.192996,0.000000,...,0.003979,0.181999,0.009983,0.099533,0.000000,0.000000,0.649248,0.162925,0.184450,0.000000
2,0.049574,0.051206,0.000000,0.042879,0.000000,0.000000,0.053247,0.331989,0.045411,0.000000,...,0.587983,0.085953,0.251808,0.025426,0.126429,0.050150,0.193393,0.270229,0.000000,0.268297
3,0.138334,0.498783,0.234630,0.322429,0.048256,0.163801,0.000000,0.136483,0.000000,0.851034,...,0.005489,0.578040,0.015156,0.449293,1.093404,0.126683,0.000000,0.069126,0.000000,0.000000
4,0.492207,0.234090,0.077175,0.030442,0.266114,0.026564,0.215106,0.000000,0.132016,0.244050,...,0.277045,0.000000,0.330117,0.081253,0.000000,0.002595,0.093908,0.127900,0.744714,0.268918

In [46]:
approximated_matrix = np.matmul(W, H)
approximated_matrix
approximated_matrix_df = pd.DataFrame(approximated_matrix, index=data.index, columns=data.columns)
approximated_matrix_df

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P91,P92,P93,P94,P95,P96,P97,P98,P99,P100
cust_1,0.147436,0.220188,0.139583,0.155453,0.105285,0.124687,0.097768,0.145012,0.084452,0.317469,...,0.132799,0.247428,0.104910,0.187391,0.400340,0.120033,0.158181,0.129900,0.102740,0.079895
cust_2,0.162851,0.170707,0.057499,0.090544,0.065996,0.034229,0.081206,0.239717,0.058122,0.200791,...,0.443461,0.156419,0.237918,0.112245,0.272354,0.055214,0.146148,0.215512,0.161208,0.232763
cust_3,0.114875,0.241239,0.156168,0.159966,0.082829,0.141996,0.092194,0.095415,0.067752,0.377088,...,0.008707,0.299283,0.027491,0.224655,0.478477,0.092122,0.166790,0.083501,0.060646,0.008917
cust_4,0.346802,0.168583,0.128427,0.023972,0.222642,0.136219,0.304258,0.096415,0.185583,0.134301,...,0.230664,0.115182,0.217769,0.104328,0.020771,0.009996,0.439146,0.196857,0.503934,0.181099
cust_5,0.167471,0.071816,0.180388,0.182861,0.245934,0.218239,0.184440,0.226447,0.230287,0.015436,...,0.136485,0.096472,0.173088,0.061091,0.046554,0.349366,0.282702,0.209158,0.067842,0.097044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cust_96,0.238438,0.106975,0.102306,0.114192,0.205641,0.098099,0.128609,0.134336,0.147615,0.081066,...,0.204458,0.026504,0.221197,0.043393,0.024142,0.202540,0.102624,0.152024,0.254618,0.160314
cust_97,0.181615,0.302646,0.252538,0.344938,0.222937,0.231636,0.060253,0.193128,0.153950,0.465173,...,0.003000,0.321127,0.119236,0.259018,0.597652,0.407201,0.015815,0.128451,0.000000,0.034757
cust_98,0.126031,0.289318,0.186203,0.203145,0.094988,0.166765,0.091067,0.116737,0.074657,0.459070,...,0.003950,0.357964,0.029875,0.269438,0.589810,0.126870,0.164190,0.093507,0.045868,0.006020
cust_99,0.308630,0.149698,0.142380,0.065154,0.234619,0.152231,0.259432,0.076085,0.187437,0.126072,...,0.123808,0.097643,0.179500,0.094878,0.024057,0.093416,0.343563,0.156585,0.412249,0.127489
cust_100,0.148301,0.274968,0.176749,0.154867,0.094734,0.165027,0.141533,0.100739,0.084485,0.418747,...,0.021076,0.346392,0.031278,0.257589,0.518882,0.060277,0.262857,0.105130,0.118466,0.016400

In [49]:
# mean average error
(data - approximated_matrix_df).abs().mean().mean()

0.19552410857135225

In [ ]:
# Pour recommander un item, on prend le mieux noté parmi ceux qu'il n'avait pas notés.
utilisateur = 'cust_5'

In [60]:
data_utilisateur = data.filter(items=[utilisateur], axis=0).transpose()
data_utilisateur['has_rated'] = (data_utilisateur[utilisateur] != 0)
data_utilisateur

        cust_5  has_rated
P1    0.900272       True
P2    0.000000      False
P3    0.000000      False
P4    0.080377       True
P5    0.085035       True
...        ...        ...
P96   0.314394       True
P97   0.260991       True
P98   0.604536       True
P99   0.000000      False
P100  0.000000      False

[100 rows x 2 columns]

In [61]:
predicted_ratings_utilisateur = approximated_matrix_df.filter(items=[utilisateur], axis=0).transpose()
predicted_ratings_utilisateur

        cust_5
P1    0.167471
P2    0.071816
P3    0.180388
P4    0.182861
P5    0.245934
...        ...
P96   0.349366
P97   0.282702
P98   0.209158
P99   0.067842
P100  0.097044

[100 rows x 1 columns]

In [94]:
# Un peu pareil que pour Pearson, on prend les meilleurs de ceux qu'on a pas encore notés
items_sorted = predicted_ratings_utilisateur[data_utilisateur['has_rated'] == False].sort_values(utilisateur, ascending=False)
items_sorted[:5].index

Index(['P39', 'P52', 'P14', 'P86', 'P72'], dtype='object')

In [111]:
# On met le tout dans une fonction
def person_based_recommandation_nnf(data, utilisateur, n_categories=5, n_recommandations=5):
    model = NMF(n_components=n_categories, init='random', max_iter=2000, random_state=0)
    W = model.fit_transform(data)
    H = model.components_
    approximated_matrix = np.matmul(W, H)
    approximated_matrix_df = pd.DataFrame(approximated_matrix, index=data.index, columns=data.columns)

    # Pour recommander un item, on prend le mieux noté parmi ceux qu'il n'avait pas notés.
    data_utilisateur = data.filter(items=[utilisateur], axis=0).transpose()
    data_utilisateur['has_rated'] = (data_utilisateur[utilisateur] != 0)
    
    predicted_ratings_utilisateur = approximated_matrix_df.filter(items=[utilisateur], axis=0).transpose()

    # Un peu pareil que pour Pearson, on prend les meilleurs de ceux qu'on a pas encore notés
    items_sorted = predicted_ratings_utilisateur[data_utilisateur['has_rated'] == False].sort_values(utilisateur, ascending=False)
    return items_sorted[:n_recommandations].index

In [112]:
# Exemples
person_based_recommandation_nnf(fake_data, 'cust_5', n_categories=15)

Index(['P17', 'P58', 'P70', 'P34', 'P52'], dtype='object')

In [104]:
person_based_recommandation_nnf(fake_data, 'cust_75', n_categories=15, n_recommandations=8)

Index(['P64', 'P25', 'P46', 'P53', 'P83', 'P49', 'P77', 'P92'], dtype='object')